FROM cfljam/pyrat

MAINTAINER helge.dzierzon@plantandfood.co.nz

ENV http_proxy http://proxy.pfr.co.nz:8080
ENV https_proxy http://proxy.pfr.co.nz:8080
ENV no_proxy web,mongo,localhost,127.0.0.1,*.pfr.co.nz,::1

ADD req_pyrat.txt req_pyrat.txt

RUN mkdir /tmp/PyKaka; \
    mkdir /tmp/rkaka;

RUN Rscript -e 'devtools::install_github("hdzierz/rkaka", ref="lod_lib")';

# test
RUN pip2.7 install --upgrade pip;\
    pip3 install --upgrade pip;\
    pip2.7 install -r req_pyrat.txt;\
    pip3 install -r req_pyrat.txt;\
    pip2.7 install git+https://github.com/hdzierz/PyKaka.git@cleanup;\
    pip3 install git+https://github.com/hdzierz/PyKaka.git@cleanup;\

    

