FROM rocker/shiny

MAINTAINER helge.dzierzon@plantandfood.co.nz

ENV http_proxy http://proxy.pfr.co.nz:8080
ENV https_proxy http://proxy.pfr.co.nz:8080
ENV no_proxy localhost,127.0.0.1,*.pfr.co.nz,::1,web

ADD install.R install.R
ADD ./shinyapps/kaka/seafood /srv/shiny-server/seafood

RUN apt-get update -y; \
	apt-get upgrade -y;

RUN    apt-get install -y libssl-dev

RUN Rscript install.R; \
	ls /srv/shiny-server/



