FROM rocker/shiny

MAINTAINER helge.dzierzon@plantandfood.co.nz

ENV http_proxy http://proxy.pfr.co.nz:8080
ENV https_proxy http://proxy.pfr.co.nz:8080
ENV no_proxy localhost,127.0.0.1,*.pfr.co.nz,::1

ADD install.R install.R
ADD shiny_apps/kaka/seafood /srv/shiny-server/

RUN apt-get update -y; \
	apt-get upgrade -y;

RUN Rscript install.R



