FROM mongo:3.2

ENV http_proxy http://proxy.pfr.co.nz:8080
ENV https_proxy http://proxy.pfr.co.nz:8080
ENV no_proxy localhost,127.0.0.1,*.pfr.co.nz,::1

COPY setup_with_env.sh /setup_with_env.sh
COPY setup.sh setup.sh

CMD ["/setup_with_env.sh"]
