FROM rocker/shiny

ENV http_proxy  http://proxy.pfr.co.nz:8080
ENV https_proxy  http://proxy.pfr.co.nz:8080
ENV ftp_proxy  http://proxy.pfr.co.nz:8080
ENV no_proxy  localhost,::1,127.0.0.1,*.pfr.co.nz

ADD install.R install.R

RUN apt-get update -y; \
	apt-get upgrade -y;

RUN Rscript install.R



