---
Data Creator : Badi James
Experiment Description : >-
    Test experiment configuration
    for Kaka
Experiment Code : 123456
Upload Date : dt(16-01-08T11:07:33Z)
Experiment Date : dt(2016-01-07)
...